src/java/com/fbaa/jpa/entities/AreaVoluntariado.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fbaa.jpa.entities;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * @author INTERNET
 */
@Entity
@Table(name = "TABLA_AREA_VOLUNTARIADO")
public class AreaVoluntariado implements Serializable {

    @Id
    @GeneratedValue
    private Long id_area_voluntariado;
    private String nombreAreaVoluntariado;

    public String getNombreAreaVoluntariado() {
        return nombreAreaVoluntariado;
    }

    public void setNombreAreaVoluntariado(String nombreAreaVoluntariado) {
        this.nombreAreaVoluntariado = nombreAreaVoluntariado;
    }

    public Long getId() {
        return id_area_voluntariado;
    }

    public void setId(Long id) {
        this.id_area_voluntariado = id;
    }

}

src/java/com/fbaa/formularios/AreaVoluntariadoBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fbaa.formularios;

import com.fbaa.jpa.DAO.GestionarAreaVoluntariadoDAO;
import com.fbaa.jpa.entities.AreaVoluntariado;
import java.io.Serializable;
import java.util.ArrayList;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

/**
 *
 * @author INTERNET
 */
@ManagedBean(name = "areaVoluntariadoBean")
@ViewScoped
public class AreaVoluntariadoBean implements Serializable{

    private AreaVoluntariado areaVoluntariado;
    private String nombreAreaVoluntariadoSeleccionada;
    private String msg;
    private final GestionarAreaVoluntariadoDAO areaVoluntariadoDAO = new GestionarAreaVoluntariadoDAO();

    @PostConstruct
    public void init() {
        areaVoluntariado = new AreaVoluntariado();
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public String getNombreAreaVoluntariadoSeleccionada() {
        return nombreAreaVoluntariadoSeleccionada;
    }

    public void setNombreAreaVoluntariadoSeleccionada(String nombreAreaVolSeleccionada) {
        this.nombreAreaVoluntariadoSeleccionada = nombreAreaVolSeleccionada;
    }

    public String crearAreaVoluntariado() {
        if (this.areaVoluntariado.getNombreAreaVoluntariado() != null) {
            areaVoluntariadoDAO.crearAreaVoluntariado(this.areaVoluntariado);
        }
        return null;
    }

    public String obtenerAreaVoluntariado() {
        if (areaVoluntariado.getId() != null) {
            AreaVoluntariado areavolFromDao;
            areavolFromDao = areaVoluntariadoDAO.obtenerAreaVoluntariadoByID(areaVoluntariado.getId());
            this.areaVoluntariado = areavolFromDao;
        }
        return null;
    }

    public String actualizarAreaVoluntariado() {

        if (this.areaVoluntariado.getId() != null) {
            areaVoluntariadoDAO.actualizarAreaVoluntariado(this.areaVoluntariado);
            limpiarTodo();
            this.msg = "Area de voluntariado actualizada exitosamente!";
        } else {
            this.msg = "Por favor seleccione una area de voluntariado!";
        }
        return null;
    }

    public String eliminarAreaVoluntariado() {
        if (this.areaVoluntariado.getId() != null) {
            areaVoluntariadoDAO.eliminarAreaVoluntariado(this.areaVoluntariado);
            limpiarTodo();
            this.msg = "Area de voluntariado eliminada exitosamente!";
        } else {
            this.msg = "Por favor seleccione una area de voluntariado!";
        }
        return null;
    }

    public ArrayList<AreaVoluntariado> getAreasVoluntariadoList() {
        return areaVoluntariadoDAO.obtenerAreasVoluntariado();
    }

    private void limpiarTodo() {
        this.areaVoluntariado.setId(null);
        this.areaVoluntariado.setNombreAreaVoluntariado("");
    }

    public AreaVoluntariado getAreaVoluntariado() {
        return areaVoluntariado;
    }

    public void setAreaVoluntariado(AreaVoluntariado areaVol) {
        this.areaVoluntariado = areaVol;
    }

    /**
     * Creates a new instance of AreaVoluntariadoBean
     */
    public AreaVoluntariadoBean() {
    }

}

src/java/com/fbaa/formularios/CommonDataBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fbaa.formularios;

import com.fbaa.jpa.entities.AreaVoluntariado;
import com.fbaa.jpa.DAO.GestionarVoluntarioDAO;
import com.fbaa.jpa.entities.Universidad;
import com.fbaa.jpa.entities.Voluntario;
import java.io.Serializable;
import java.util.ArrayList;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

/**
 *
 * @author Juan Pablo Alvis <juanpabloalvis@gmail.com>
 */
@ManagedBean(name = "commons")
@RequestScoped
public class CommonDataBean implements Serializable {

    public CommonDataBean() {
    }

    
    private static final long serialVersionUID = 6L;
    private String titulo;
    private final GestionarVoluntarioDAO mvol = new GestionarVoluntarioDAO();

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public ArrayList<Voluntario> getVoluntariosList() {
        return mvol.obtenerVoluntarios();
    }

    public ArrayList<Universidad> getUniversidadesList() {
        return mvol.obtenerUniversidades();
    }

    public ArrayList<AreaVoluntariado> getAreaVoluntariadoList() {
        return mvol.obtenerAreasVoluntariado();
    }

    public Voluntario getVoluntarioByDocumentoIdentidad(Long cedula) {
        return mvol.obtenerVoluntarioPorDocumentoIdentidad(cedula);
    }

}

src/java/com/fbaa/formularios/GeneroBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fbaa.formularios;

import com.fbaa.jpa.DAO.GestionarGeneroDAO;
import com.fbaa.jpa.entities.AreaVoluntariado;
import com.fbaa.jpa.entities.Genero;
import java.io.Serializable;
import java.util.ArrayList;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

/**
 *
 * @author INTERNET
 */
@ManagedBean(name = "generoBean")
@ViewScoped
public class GeneroBean implements Serializable {

    private Genero genero;
    private String nombreGeneroSeleccionado;
    private String msg;
    private final GestionarGeneroDAO generosVoluntariadoDAO = new GestionarGeneroDAO();

    @PostConstruct
    public void init() {
        genero = new Genero();
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public String getGeneroSeleccionado() {
        return nombreGeneroSeleccionado;
    }

    public void setNombreGeneroSeleccionado(String nomGeneroSeleccionado) {
        this.nombreGeneroSeleccionado = nomGeneroSeleccionado;
    }

    public String obtenerGenero() {
        if (genero.getId() != null) {
            Genero generoVolFromDao;
            generoVolFromDao = generosVoluntariadoDAO.obtenerGeneroByID(genero.getId());
            this.genero = generoVolFromDao;
        }
        return null;
    }

    private void limpiarTodo() {
        this.genero.setId(null);
        this.genero.setNombreGenero("");
    }

    public Genero getGenero() {
        return genero;
    }

    public void setGenero(Genero genero) {
        this.genero = genero;
    }

    public String getNombreGeneroSeleccionado() {
        return nombreGeneroSeleccionado;
    }

    public ArrayList<Genero> getGenerosList() {
        return generosVoluntariadoDAO.obtenerGeneros();
    }

    /**
     * Creates a new instance of AreaVoluntariadoBean
     */
    public GeneroBean() {
    }

}

src/java/com/fbaa/formularios/UniversidadBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fbaa.formularios;

import com.fbaa.jpa.DAO.GestionarUniversidadDAO;
import com.fbaa.jpa.entities.Universidad;
import java.io.Serializable;
import java.util.ArrayList;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

/**
 *
 * @author INTERNET
 */
@ManagedBean(name = "universidadBean")
@ViewScoped
public class UniversidadBean implements Serializable {

    private Universidad universidad;
    private String nombreUniversidadSeleccionada;
    private String msg;
    private final GestionarUniversidadDAO universidadesDAO = new GestionarUniversidadDAO();

    @PostConstruct
    public void init() {
        universidad = new Universidad();
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public String getNombreUniversidadSeleccionada() {
        return nombreUniversidadSeleccionada;
    }

    public void setNombreUniversidadSeleccionada(String nombreUniversidadSeleccionada) {
        this.nombreUniversidadSeleccionada = nombreUniversidadSeleccionada;
    }

    public String crearUniversidad() {
        if (this.universidad.getNombreUniversidad() != null) {
            universidadesDAO.crearUniversidad(this.universidad);
        }
        return null;
    }

    public String obtenerUniversidad() {
        if (universidad.getId() != null) {
            Universidad univFromDAO;
            univFromDAO = universidadesDAO.obtenerUniversidadByID(universidad.getId());
            this.universidad = univFromDAO;
        }
        return null;
    }

    public String actualizarUniversidad() {

        if (this.universidad.getId() != null) {
            universidadesDAO.actualizarUniversidad(this.universidad);
            limpiarTodo();
            this.msg = "Universidad actualizada exitosamente!";
        } else {
            this.msg = "Por favor seleccione una universidad!";
        }
        return null;
    }

    public String eliminarUniversidad() {
        if (this.universidad.getId() != null) {

            universidadesDAO.eliminarUniversidad(this.universidad);
            limpiarTodo();
            this.msg = "Universidad eliminada exitosamente!";
        } else {
            this.msg = "Por favor seleccione una universidad!";
        }
        return null;
    }

    public ArrayList<Universidad> getUniversidadesList() {
        return universidadesDAO.obtenerUniversidades();
    }

    private void limpiarTodo() {
        this.universidad.setId(null);
        this.universidad.setNombreUniversidad("");
    }

    public Universidad getUniversidad() {
        return universidad;
    }

    public void setUniversidad(Universidad universidad) {
        this.universidad = universidad;
    }

    /**
     * Creates a new instance of UniversidadBean
     */
    public UniversidadBean() {
    }

}

src/java/com/fbaa/formularios/VoluntarioBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fbaa.formularios;

import com.fbaa.jpa.DAO.GestionarVoluntarioDAO;
import com.fbaa.jpa.entities.AreaVoluntariado;
import com.fbaa.jpa.entities.Universidad;
import com.fbaa.jpa.entities.Voluntario;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author INTERNET
 */
@ManagedBean(name = "voluntarioBean")
@SessionScoped
public class VoluntarioBean implements Serializable{

    private Voluntario voluntario;
    private String[] diasSemana;

    private String msg;
    private final GestionarVoluntarioDAO epsDAO = new GestionarVoluntarioDAO();

    //gestionarVoluntarioDAO
    @PostConstruct
    public void init() {
        voluntario = new Voluntario();
//        AreaVoluntariado areaVoluntariado = new AreaVoluntariado();
//        areaVoluntariado.setId(1L);
//        voluntario.setAreaVoluntariado(areaVoluntariado);
//        Universidad universidad = new Universidad();
//        areaVoluntariado.setId(1L);
//        voluntario.setUniversidad(universidad);
//        EPS eps = new EPS();
//        eps.setId(1L);
//        voluntario.setEPS(eps);
//        Genero genero = new Genero();
//        genero.setId(1L);
//        voluntario.setGenero(genero);
    }

    public String[] getDiasSemanaValores() {
        diasSemana = new String[7];
        diasSemana[0] = "Lunes";
        diasSemana[1] = "Martes";
        diasSemana[2] = "Miercoles";
        diasSemana[3] = "Jueves";
        diasSemana[4] = "Viernes";
        diasSemana[5] = "Sabado";
        diasSemana[6] = "Domingo";

        return diasSemana;
    }

    public String[] getDiasSemana() {
        return diasSemana;
    }

    public void setDiasSemana(String[] diasSemana) {
        this.diasSemana = diasSemana;
    }

    public void calcularDiasSemanaToBin() {
        StringBuilder dias = new StringBuilder("00000000");
        // {1,4,7} -->01001010
        //int i = 0;
        for (String diasSemana1 : getDiasSemana()) {
            dias.setCharAt(Arrays.asList(getDiasSemanaValores()).indexOf(diasSemana1), '1');
        }
        voluntario.setDias(dias.toString());
    }

    public void calcularBinToDiasSemana() {
        String dias = voluntario.getDias();
        List<String> scripts = new ArrayList<>();
        for (int i = 0; i < dias.length(); i++) {
            System.out.println("-->" + diasSemana.length);
            if (dias.charAt(i) == '1') {
                scripts.add(i + "");
            }
            diasSemana = scripts.toArray(new String[scripts.size()]);
        }
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public String crearVoluntario() {
        if (this.voluntario.getCedula() != 0) {
            calcularDiasSemanaToBin();
            epsDAO.guardarVoluntario(this.voluntario);
        }
        voluntario = new Voluntario();
        return null;
    }

    public String obtenerVoluntario() {
        if (voluntario.getId() != null) {
            Voluntario voluntarioFromDao;
            voluntarioFromDao = epsDAO.obtenerVoluntario(voluntario.getId());
            this.voluntario = voluntarioFromDao;
        }
        return null;
    }

    public String obtenerVoluntarioByCedula() {
        if (voluntario.getId() != null) {
            Voluntario voluntarioFromDao;
            voluntarioFromDao = epsDAO.obtenerVoluntarioPorDocumentoIdentidad(voluntario.getCedula());
            this.voluntario = voluntarioFromDao;
        }
        return null;
    }

    public String actualizarVoluntario() {

        if (this.voluntario.getId() != null) {
            epsDAO.actualizarVoluntario(this.voluntario);
            limpiarTodo();
            this.msg = "Voluntario actualizado exitosamente!";
        } else {
            this.msg = "Por favor seleccione un Voluntario!";
        }
        return null;
    }

    public String eliminarVoluntario() {
        if (this.voluntario.getId() != null) {
            epsDAO.eliminarVoluntario(this.voluntario);
            limpiarTodo();
            this.msg = "Voluntario eliminado exitosamente!";
        } else {
            this.msg = "Por favor seleccione un voluntario!";
        }
        return null;
    }

    public ArrayList<Voluntario> getVoluntariosList() {
        return epsDAO.obtenerVoluntarios();
    }

    private void limpiarTodo() {
        this.voluntario.setId(0L);
        this.voluntario.setCedula(0L);
        this.voluntario.setApellidos("");
        this.voluntario.setNombres("");
    }

    public void limpiarFormulario() {
        this.voluntario.setId(0L);
        this.voluntario.setCedula(0L);
        this.voluntario.setApellidos("");
        this.voluntario.setNombres("");
        Universidad universidad = new Universidad();
        AreaVoluntariado areaVoluntariado = new AreaVoluntariado();
        // this.voluntario = new Voluntario();
        this.voluntario.setAreaVoluntariado(areaVoluntariado);
        this.voluntario.setUniversidad(universidad);

    }

    public Voluntario getVoluntario() {
        return voluntario;
    }

    public void setVoluntario(Voluntario voluntarioP) {
        this.voluntario = voluntarioP;
    }

    /**
     * Creates a new instance of EPSBean
     */
    public VoluntarioBean() {
    }

}

web/secured/BuscarVoluntario.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title><h:outputText value="#{msg['app_titulo_fbaa']}" /></title>
    </h:head>
    <h:body>
        <ui:composition template="/templates/commonLayout.xhtml">

            <ui:define name="content">
                <!--                <h:outputScript target="head" >
                                    $ = jQuery;
                                    $(function () {
                                    //alert("FUNCIONA")
                
                                    });   
                                </h:outputScript>-->
                <script type="text/javascript">
                    $ = jQuery;
                    $(function () {
                        //alert("Revisar Datepicker")
                        // Datepicker
                        //            $('#registoVoluntarios\\:fechaIngresoDp').click(function(){
                        //alert("Loaded")
                        //});
                        // $('#registoVoluntarios\\:fechaIngresoDp').datetimepicker();

                    });

                </script>
                <div class="col-xs-12 col-sm-9" data-spy="scroll" data-target="#sidebar-nav">
                    <br/>
                    <br/>


                    <h:form id="buscarVoluntario">
                        <h:outputText value="Número de Cédula: "></h:outputText>
                        <h:inputText id="inputTxt4" value="#{busquedaVoluntario.cedulaBusqueda}"/>
                        <br/>
                        <h:outputText value=" "></h:outputText>
                        <h:commandButton  id="cmdBtn2" value="Buscar Voluntario" class="btn btn-default btn-primary" actionListener="#{busquedaVoluntario.findVoluntarioByID()}">
                            <f:ajax id="abtn" execute="inputTxt4" render="voluntarioBuscado cbxArea cbxUniversidad"/>  
                        </h:commandButton>
                        <h:panelGroup id="voluntarioBuscado">
                            <h:panelGroup rendered="#{busquedaVoluntario.cedulaBusqueda != null and busquedaVoluntario.voluntario != null and busquedaVoluntario.cedulaBusqueda !=0}" >


                                <h3>
<!--                                    <h:outputText value="#{voluntario.titulo != null ? voluntario.titulo : msg['gestionar_voluntario']}" />-->
                                </h3>
                                <h:messages/>
                                <table border="1">
                                    <tr>
                                        <td>Cedula:</td>
                                        <td><h:inputText size="10" value="#{busquedaVoluntario.voluntario.cedula}" /></td>
                                    </tr>
                                    <tr>
                                        <td>Nombre:</td>
                                        <td><h:inputText size="20" value="#{busquedaVoluntario.voluntario.nombres}" /></td>
                                    </tr>
                                    <tr>
                                        <td>Apellido:</td>
                                        <td><h:inputText size="20" value="#{busquedaVoluntario.voluntario.apellidos}" /></td>
                                    </tr>
                                    <tr>
                                        <td>Telefono:</td>
                                        <td><h:inputText size="25" value="#{busquedaVoluntario.voluntario.telefono}" /></td>
                                    </tr>
                                    <tr>
                                        <td>Correo:</td>
                                        <td><h:inputText size="20" value="#{busquedaVoluntario.voluntario.correo}" /></td>
                                    </tr>
                                    <tr>
                                        <td>Genero :</td>
                                        <td><h:selectOneMenu  value="#{busquedaVoluntario.voluntario.genero.id}" id="cbxGenero" >
                                                <f:selectItem itemValue="#{null}" itemLabel="Seleccione uno"/>
                                                <f:selectItems value="#{generoBean.generosList}" var="genero" itemValue="#{genero.id}" itemLabel="#{genero.nombreGenero}" />
                                            </h:selectOneMenu></td>
                                    </tr>
                                    <tr>
                                        <td>Nivel de estudios :</td>
                                        <td><h:inputText size="30" value="#{busquedaVoluntario.voluntario.nivelEstudios}" /></td>
                                    </tr>
                                    <tr>
                                        <td>Area de Voluntariado:</td>
                                        <td>
                                            <!--
                                            http://jdevelopment.nl/automatic-toobject-conversion-jsf-selectonemenu/
                                            http://stackoverflow.com/questions/6848970/how-to-prepopulate-a-hselectonemenu-with-complex-objects-entities-from-a-db-->


                                            <h:selectOneMenu value="#{busquedaVoluntario.voluntario.areaVoluntariado.id}" id="cbxArea">
                                                <f:selectItem itemValue="#{null}" itemLabel="Seleccione uno"/>
                                                <f:selectItems value="#{areaVoluntariadoBean.areasVoluntariadoList}" var="area" itemValue="#{area.id}" itemLabel="#{area.nombreAreaVoluntariado}" />
                                            </h:selectOneMenu>

                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Universidad:</td>
                                        <td>
                                            <h:selectOneMenu value="#{busquedaVoluntario.voluntario.universidad.id}" id="cbxUniversidad">
                                                <f:selectItem itemValue="#{null}" itemLabel="Seleccione uno"/>
                                                <f:selectItems value="#{universidadBean.universidadesList}" var="univ" itemValue="#{univ.id}" itemLabel="#{univ.nombreUniversidad}" />
                                            </h:selectOneMenu>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>EPS:</td>
                                        <td>
                                            <h:selectOneMenu value="#{busquedaVoluntario.voluntario.EPS.id}" id="cbxEps">
                                                <f:selectItem itemValue="#{null}" itemLabel="Seleccione uno"/>
                                                <f:selectItems value="#{epsBean.EPSsList}" var="epsVar" itemValue="#{epsVar.id}" itemLabel="#{epsVar.nombreEPS}" />
                                            </h:selectOneMenu>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Carrera:</td>
                                        <td><h:inputText size="30" value="#{busquedaVoluntario.voluntario.carrera}" /></td>
                                    </tr>
                                    <tr>
                                        <td>Fecha Ingreso:</td>
                                        <td>
                                            <h:inputText size="40" readonly="true" value="#{busquedaVoluntario.voluntario.fechaIngreso}" id="fechaIngresoDp">
                                                <!--                                                <f:convertDateTime pattern="yyyy-MM-dd" />-->
                                            </h:inputText>


                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Intensidad Horas Requeridas:</td>
                                        <td><h:inputText size="10" value="#{busquedaVoluntario.voluntario.intensidadHoras}" /></td>
                                    </tr>
                                    <tr>
                                        <td>Dias en que realiza la práctica:</td>
<!--                                        <td><h:inputText size="15" value="#{busquedaVoluntario.voluntario.dias}" /></td>-->
                                        <td><h:selectManyCheckbox value="#{busquedaVoluntario.diasSeleccionados}">
                                                <f:selectItems value="#{busquedaVoluntario.diasSemanaValores}" />
                                            </h:selectManyCheckbox></td>
                                    </tr>
                                    <tr>
                                        <td>Horarios:</td>
                                        <td><h:inputText size="15" value="#{busquedaVoluntario.voluntario.horarios}"/></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                </table>
                                <br/>
                                <table>
                                    <tr>
                                        <td align="center"> <h:commandButton value="Actualizar Datos" action="#{busquedaVoluntario.updateAction(busquedaVoluntario.voluntario)}" class="btn btn-default btn-primary"/></td>
                                        <td align="center"><h:commandButton value="Nueva búsqueda" action="#{busquedaVoluntario.limpiarFormulario}" class="btn btn-default btn-primary" /></td>
                                        <td align="center"><h:commandButton value="Historial Horas" action="#{navegacionBean.redirectHistorialHoras()}" class="btn btn-default btn-primary" /></td>
                                        <td align="center"><h:commandButton value="Generar Certificación" action="#{navegacionBean.redirectGenerarCertificacionVoluntario}" class="btn btn-default btn-primary" /></td>
                                        <br/>
                                        <td align="center"> <h:commandButton value="Registrar huella (Manual)" action="#{busquedaVoluntario.limpiarFormulario}" class="btn btn-default btn-primary" /></td>

                                    </tr>
                                </table>
                                <br/>





                                <br/><br/>
                            </h:panelGroup>

                        </h:panelGroup>

                    </h:form>
                </div>
                <h:outputStylesheet name="bootstrap-3.3.4/css/bootstrap-datetimepicker.min.css"/>
                <script src="../resources/bootstrap-3.3.4/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
                <!--                <link href="../resources/bootstrap-3.3.4/css/bootstrap-datetimepicker.min.css" rel="stylesheet" type="text/css"/>-->
            </ui:define>

            <br/><br/>
            <br/><br/>
            <br/><br/>
        </ui:composition>
    </h:body>
</html>