src/java/com/fbaa/formularios/CommonDataBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fbaa.formularios;

import com.fbaa.jpa.entities.AreaVoluntariado;
import com.fbaa.jpa.DAO.GestionarVoluntarioDAO;
import com.fbaa.jpa.entities.Universidad;
import com.fbaa.jpa.entities.Voluntario;
import java.io.Serializable;
import java.util.ArrayList;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

/**
 *
 * @author Juan Pablo Alvis <juanpabloalvis@gmail.com>
 */
@ManagedBean(name = "commons")
@RequestScoped
public class CommonDataBean implements Serializable {

    public CommonDataBean() {
    }

    
    private static final long serialVersionUID = 6L;
    private String titulo;
    private final GestionarVoluntarioDAO mvol = new GestionarVoluntarioDAO();

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public ArrayList<Voluntario> getVoluntariosList() {
        return mvol.obtenerVoluntarios();
    }

    public ArrayList<Universidad> getUniversidadesList() {
        return mvol.obtenerUniversidades();
    }

    public ArrayList<AreaVoluntariado> getAreaVoluntariadoList() {
        return mvol.obtenerAreasVoluntariado();
    }

    public Voluntario getVoluntarioByDocumentoIdentidad(Long cedula) {
        return mvol.obtenerVoluntarioPorDocumentoIdentidad(cedula);
    }

}

src/java/com/fbaa/formularios/UtilBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fbaa.formularios;

import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ApplicationScoped;

/**
 *
 * @author INTERNET
 */
@ManagedBean(name = "utilBean")
@ApplicationScoped
public class UtilBean implements Serializable{

    public String getToday() {
        DateFormat dateFormat = new SimpleDateFormat("dd 'de' MMMM 'de' yyyy");
        Date date = new Date();
        return dateFormat.format(date);
    }
}

src/java/com/fbaa/login/LoginBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fbaa.login;

import com.fbaa.formularios.NavegacionBean;
import com.fbaa.jpa.DAO.GestionarUsuarioAutenticadoDAO;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import org.apache.commons.io.IOUtils;

/**
 *
 * @author INTERNET
 */
// @Named(value = "usuario") este no funciona porque no se usa CFI
@ManagedBean(name = "loginBean")
@SessionScoped
public class LoginBean implements Serializable {

    private static final long serialVersionUID = 2L;

    private String usuario;
    private String contrasena;
    private String mensaje_respuesta;
    private boolean loggedIn;
    private final GestionarUsuarioAutenticadoDAO usuariosAutenticados = new GestionarUsuarioAutenticadoDAO();

    // TODO revisar si se puede utilizar el operador New()
    @ManagedProperty(value = "#{navegacionBean}")
    private final NavegacionBean navegacionBean = new NavegacionBean();

    /**
     * Creates a new instance of Usuario
     */
    public LoginBean() {
    }

    public String doLogin() throws NoSuchAlgorithmException {
        InputStream in = null;
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            in = IOUtils.toInputStream(contrasena, "UTF-8");

            byte byteData[] = md.digest();
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < byteData.length; i++) {
                sb.append(Integer.toString((byteData[i] & 0xff) + 0x100, 16).substring(1));
            }

            // Get every user from our sample database :)
            if (usuariosAutenticados.usuarioAutenticado(usuario, sb.toString()) != null) {
                loggedIn = true;
                return navegacionBean.redirectToIndex();
            }   // Set login ERROR

        } catch (IOException ex) {
            Logger.getLogger(LoginBean.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                in.close();
            } catch (IOException ex) {
                Logger.getLogger(LoginBean.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        FacesMessage msg = new FacesMessage("Error de autenticación!", "ERROR MSG");
        msg.setSeverity(FacesMessage.SEVERITY_ERROR);
        FacesContext.getCurrentInstance().addMessage(null, msg);
        // To to login page
        return navegacionBean.toLogin();
    }

    /**
     * Logout operation.
     *
     * @return
     */
    public String doLogout() {
        // Set the paremeter indicating that user is logged in to false
        loggedIn = false;
        // Set logout message
        FacesMessage msg = new FacesMessage("Logout success!", "INFO MSG");
        msg.setSeverity(FacesMessage.SEVERITY_INFO);
        FacesContext.getCurrentInstance().addMessage(null, msg);
        this.setMensaje_respuesta("Usuario es correcto");
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        return navegacionBean.toIndex();
    }

    public void setNavegacionBean(NavegacionBean navegacionBean) {
        navegacionBean = navegacionBean;
    }

    public String loginInfo() {
        if (this.getUsuario().equals("admin") && this.getContrasena().equals("admin")) {
            this.setMensaje_respuesta("Usuario es correcto");
        } else if (this.getUsuario().equals("") && this.getContrasena().equals("")) {
            this.setMensaje_respuesta("Por favor ingrese nombre y contraseña");
        } else {
            this.setMensaje_respuesta("Usuario incorrecto");
        }

        return getMensaje_respuesta();
    }

    /**
     * Get the value of mensaje_respuesta
     *
     * @return the value of mensaje_respuesta
     */
    public String getMensaje_respuesta() {
        return mensaje_respuesta;
    }

    /**
     * Set the value of mensaje_respuesta
     *
     * @param mensaje_respuesta new value of mensaje_respuesta
     */
    private void setMensaje_respuesta(String mensaje_respuesta) {
        this.mensaje_respuesta = mensaje_respuesta;
    }

    /**
     * Get the value of contrasena
     *
     * @return the value of contrasena
     */
    public String getContrasena() {
        return contrasena;
    }

    /**
     * Set the value of contrasena
     *
     * @param contrasena new value of contrasena
     */
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    /**
     * Get the value of usuario
     *
     * @return the value of usuario
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * Set the value of usuario
     *
     * @param usuario new value of usuario
     */
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public boolean isLoggedIn() {
        return loggedIn;
    }

    public void setLoggedIn(boolean loggedIn) {
        this.loggedIn = loggedIn;
    }
}

src/java/com/fbaa/util/UtilTestBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fbaa.util;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import javax.enterprise.context.SessionScoped;
import javax.faces.bean.ManagedBean;

/**
 *
 * @author Juan Pablo Alvis <juanpabloalvis@gmail.com>
 */
/**
 *
 * @author Juan Pablo Alvis <juanpabloalvis@gmail.com>
 */
@ManagedBean(name = "utils") //@Named este no funciona porque no se usa CFI
@SessionScoped
public class UtilTestBean implements Serializable {

    private List<PizzaObject> results = new ArrayList<>();
    private String nombre;
    static final Logger LOGGER = Logger.getLogger(UtilTestBean.class.getName());

    public UtilTestBean() {
        LOGGER.info("Iniciando Bean");
        List<PizzaObject.Size> pizaSize = new ArrayList<>();
        pizaSize.add(new PizzaObject.Size(1, 1));
        pizaSize.add(new PizzaObject.Size(2, 2));
        pizaSize.add(new PizzaObject.Size(3, 3));
        List<PizzaObject.Topping> pizaTopping = new ArrayList<>();
        pizaTopping.add(new PizzaObject.Topping(4, 4));
        pizaTopping.add(new PizzaObject.Topping(5, 5));
        pizaTopping.add(new PizzaObject.Topping(6, 6));
        PizzaObject.Pizza piza = new PizzaObject.Pizza();
        piza.setNombre("peperoni");
        piza.setSalsa("de la cas");
        PizzaObject pizzaObject = new PizzaObject();
        pizzaObject.setPizza(piza);
        pizzaObject.setSizeList(pizaSize);
        pizzaObject.setToppingList(pizaTopping);
        nombre = "";
        results.add(pizzaObject);
        results.add(pizzaObject);
    }

    public List<PizzaObject> getResults() {
        return results;
    }

    public void setResults(List<PizzaObject> results) {
        this.results = results;
    }

    public String getNombre() {
        return ResourcesUtil.getString("#{msg['app.saludo']}") + nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public void getNombreFromAjax() {

    }

    // CLASES ESTATICAS PARA RADIO BUTTON ANIDADO
    public static class PizzaObject {

        private Pizza pizza;
        private List<Size> sizeList;
        private List<Topping> toppingList;

        public PizzaObject() {
        }

        public PizzaObject(Pizza pizza, List<Size> sizeList, List<Topping> toppingList) {
            this.pizza = pizza;
            this.sizeList = sizeList;
            this.toppingList = toppingList;
        }

        public Pizza getPizza() {
            return pizza;
        }

        public void setPizza(Pizza pizza) {
            this.pizza = pizza;
        }

        public List<Size> getSizeList() {
            return sizeList;
        }

        public void setSizeList(List<Size> sizeList) {
            this.sizeList = sizeList;
        }

        public List<Topping> getToppingList() {
            return toppingList;
        }

        public void setToppingList(List<Topping> toppingList) {
            this.toppingList = toppingList;
        }

        public static class Size {

            public int sizeID;
            public int diameter;

            public Size() {
            }

            
            public Size(int sizeID, int diameter) {
                this.sizeID = sizeID;
                this.diameter = diameter;
            }

            // getter and setter
            public int getSizeID() {
                return sizeID;
            }

            public void setSizeID(int sizeID) {
                this.sizeID = sizeID;
            }

            public int getDiameter() {
                return diameter;
            }

            public void setDiameter(int diameter) {
                this.diameter = diameter;
            }
        }

        public static class Topping {

            public int sizeID;
            public int diameter;

            public Topping(int sizeID, int diameter) {
                this.sizeID = sizeID;
                this.diameter = diameter;
            }

            // getter and setter
            public int getSizeID() {
                return sizeID;
            }

            public void setSizeID(int sizeID) {
                this.sizeID = sizeID;
            }

            public int getDiameter() {
                return diameter;
            }

            public void setDiameter(int diameter) {
                this.diameter = diameter;
            }
        }

        public static class Pizza {

            private String nombre;
            private String salsa;

            public Pizza() {
            }

            public Pizza(String nombre, String salsa) {
                this.nombre = nombre;
                this.salsa = salsa;
            }

            public String getNombre() {
                return nombre;
            }

            public void setNombre(String nombre) {
                this.nombre = nombre;
            }

            public String getSalsa() {
                return salsa;
            }

            public void setSalsa(String salsa) {
                this.salsa = salsa;
            }

        }
    }

}

web/FormatoVoluntariado.xhtml
<ui:composition template="/templates/commonLayout.xhtml" xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core">
    <ui:define name="content">
        <!--                <b>Formato Voluntariado</b>
                        * Añadir validaciones de fecha obligatoria
                        * Añadir roles que permitan leer y escribir ciertos datos dependiendo el usuario.
                        * Unificar las plantillas.
                        * Diferencias entre voluntario, empresa, practica, 
                        * Intencidad horarias requeridas, dedicacion por semanas.
                        * Generar certificado de Horas.
                        * EPS
                        * Descargar archivos en pdf
                        * Generar reportes de participantes-->

        <h:form>
            <h3>Consultar voluntario</h3>
            <table>

                <tr>
                    <td>Cedula :</td>
                    <td><h:inputText size="10" value="#{voluntario.vol.cedula}" >
                            <f:validateLongRange minimum = "8" maximum = "10">
                            </f:validateLongRange>
                        </h:inputText></td>
                </tr>
                <tr>
                    <td>Nombre :</td>
                    <td><h:inputText size="20" value="#{voluntario.vol.nombres}" /></td>
                </tr>
                <tr>
                    <td>Apellido :</td>
                    <td><h:inputText size="20" value="#{voluntario.vol.apellidos}" /></td>
                </tr>
                <tr>
                    <td>Correo :</td>
                    <td><h:inputText size="10" value="#{voluntario.vol.correo}" /></td>
                </tr>
            </table>
            <br/>
            <!-- Agregar uno nuevo  -->
            <h:commandButton value="Consultar" action="#{voluntario.addAction}" />
            <br/>
            <br/>
            <!-- Listado de voluntarios -->
            <h:dataTable value="#{voluntario.voluntariosList}" var="o"
                         styleClass="order-table"
                         headerClass="order-table-header"
                         rowClasses="order-table-odd-row,order-table-even-row"
                         border="1"
                         >
                <h:column>

                    <f:facet name="header">Action</f:facet>

                    <h:commandLink value="Delete" action="#{order.deleteAction(o)}" />

                </h:column>

                <h:column>
                    <!-- column header -->
                    <f:facet name="header">Cedula</f:facet>
                    <!-- row record -->
                    #{o.cedula}
                </h:column>

                <h:column>
                    <f:facet name="header">Nombres</f:facet>
                        #{o.nombres}
                </h:column>

                <h:column>
                    <f:facet name="header">Apellidos</f:facet>
                        #{o.apellidos}
                </h:column>
                <h:column>
                    <f:facet name="header">Telefono</f:facet>
                        #{o.telefono}
                </h:column>
                <h:column>
                    <f:facet name="header">Correo</f:facet>
                        #{o.correo}
                </h:column>
                <h:column>
                    <f:facet name="header">Area Voluntariado</f:facet>
                        #{o.areaVoluntariado}
                </h:column>
                <h:column>
                    <f:facet name="header">Género</f:facet>
                        #{o.genero}
                </h:column>
                <h:column>
                    <f:facet name="header">Area Voluntariado</f:facet>
                        #{o.areaVoluntariado}
                </h:column>
                <h:column>
                    <f:facet name="header">Nivel de estudios</f:facet>
                        #{o.nivelEstudios}
                </h:column>
                <h:column>
                    <f:facet name="header">Universidad</f:facet>
                        #{o.universidad}
                </h:column>
                <h:column>
                    <f:facet name="header">Carrera</f:facet>
                        #{o.carrera}
                </h:column>
                <h:column>
                    <f:facet name="header">Fecha Ingreso</f:facet>
                        #{o.fechaIngreso}
                </h:column>
                <h:column>
                    <f:facet name="header">Clase de Voluntariado</f:facet>
                        #{o.claseVoluntariado}
                </h:column>
                <h:column>
                    <f:facet name="header">Intensidad Horas</f:facet>
                        #{o.intensidadHoras}
                </h:column>
                <h:column>
                    <f:facet name="header">Días</f:facet>
                        #{o.dias}
                </h:column>
                <h:column>
                    <f:facet name="header">Horarios</f:facet>
                        #{o.horarios}
                </h:column>
            </h:dataTable>
        </h:form>
    </ui:define>
</ui:composition>

web/GenerarCertificacionVoluntario.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title><h:outputText value="#{msg['app_titulo_fbaa']}" /></title>
    </h:head>
    <h:body>
        <ui:composition template="/templates/commonLayout.xhtml">

            <ui:define name="content">

                <script type="text/javascript">
                    var pdf = new jsPDF('p', 'pt', 'letter');
                    // var pdf = new jsPDF();

                    $ = jQuery;
                    $(function () {
                        specialElementHandlers = {
                            // element with id of "bypass" - jQuery style selector
                            '#bypass': function (element, renderer) {
                                // true = "handled elsewhere, bypass text extraction"
                                return true;
                            }
                        }
                    });


                </script>
                <div class="col-xs-12 col-sm-9" data-spy="scroll" data-target="#sidebar-nav" id="formatoCertificacion">
                    <br/>
                    <br/>
                    <br/>
                    <h:form id="formCertificacion">
                        <h:outputText value="Realizar Calificacion a: #{busquedaVoluntario.voluntario.nombres} #{busquedaVoluntario.voluntario.apellidos}"/>
                        <br/>
                        <br/>
                        <br/>
                        <h:panelGrid id="panel1" columns="3" border="1"
                                     cellpadding="5" cellspacing="5">
                            <f:facet name="header">
                                <h:outputText value="Resumen"/>
                            </f:facet>
                            <h:outputLabel value="Concepto"/>
                            <h:outputLabel value="Califiacion (1-5)" />
                            <h:outputLabel value=""/>

                            <h:outputLabel value="Planificación y organización del trabajo"/>
                            <h:selectOneRadio value="#{busquedaVoluntario.valPlan}" required="true" id="r1" requiredMessage="#{msg['app.pagina.generarCertificacionVoluntario']}">
                                <!--                                <f:validateRegex pattern="((?=.*[a-z]).{6,})" />-->
                                <f:selectItems value="#{busquedaVoluntario.conpPlan}" />
                            </h:selectOneRadio>
                            <h:message for="r1" style="color:red" />

                            <h:outputLabel value="Puntualidad "/>
                            <h:selectOneRadio value="#{busquedaVoluntario.valPunt}" required="true" id="r2" requiredMessage="#{msg['app.pagina.generarCertificacionVoluntario']}">
                                <f:selectItems value="#{busquedaVoluntario.conpPunt}" />
                            </h:selectOneRadio>
                            <h:message for="r2" style="color:red" />

                            <h:outputLabel value="Relaciones Interpersonales" />
                            <h:selectOneRadio value="#{busquedaVoluntario.valRelaci}" required="true" id="r3" requiredMessage="#{msg['app.pagina.generarCertificacionVoluntario']}">
                                <f:selectItems value="#{busquedaVoluntario.conpRelaci}" />
                            </h:selectOneRadio>
                            <h:message for="r3" style="color:red" />
                            <h:outputLabel value="Cumplimiento con los compromisos establecidos"/>
                            <h:selectOneRadio value="#{busquedaVoluntario.valCumpli}" required="true" id="r4" requiredMessage="#{msg['app.pagina.generarCertificacionVoluntario']}">
                                <f:selectItems value="#{busquedaVoluntario.conpCumpli}" />
                            </h:selectOneRadio>
                            <h:message for="r4" style="color:red" />
                            <h:outputLabel value="Logro del objetivo definido para la práctica"/>
                            <h:selectOneRadio value="#{busquedaVoluntario.valLogro}" required="true" id="r5" requiredMessage="#{msg['app.pagina.generarCertificacionVoluntario']}">
                                <f:selectItems value="#{busquedaVoluntario.conpLogro}" />
                            </h:selectOneRadio>
                            <h:message for="r5" style="color:red" />
                        </h:panelGrid>
                        <br/>

                        <br/>                       
                        <h:outputText value="  "/>
                        <h:commandButton value="Generar PDF" action="#{certifiacionBean.PDF}" class="btn btn-default btn-primary" >
                            
                        </h:commandButton>
                        <h:commandButton value="Generar Word" action="#{certifiacionBean.DOCX}" class="btn btn-default btn-primary" />
                        <h:commandButton value="Regresar" action="#{navegacionBean.redirectToBuscarVoluntario()}" class="btn btn-default btn-primary" />
                    </h:form>
                </div>
                <div id="bypass"></div>
            </ui:define>
            <br/><br/>
            <br/><br/>
            <br/><br/>
        </ui:composition>
    </h:body>
</html>

web/autorizados.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Autorizados</title>
    </h:head>
    <h:body>
        <h:form>
            <h:outputText id="oTxt1" value="#{usuario.loginInfo()}">xx</h:outputText>
        </h:form>
    </h:body>
</html>

web/error.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      template="/templates/bootstrap.xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <br/>
        <br/>
        <f:loadBundle basename="com.fbaa.jsf.resources.mensajes" var="msg"/>
        <!--        <meta charset="utf-8"/> 
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                
                <h:outputStylesheet name="bootstrap-3.3.4/css/bootstrap.min.css"/>
                <h:outputStylesheet name="bootstrap-3.3.4/css/bootstrap-theme.min.css"/>-->
        <ui:define name="title">
            <h:outputText value="Por favor ingrese sus datos" />
        </ui:define>

    </h:head>
    <h:body>

        <ui:composition template="/templates/commonLayout.xhtml">
            <ui:define name="content">
                <h1>Algo no está bien</h1>
                <h2>Ha ocurrido un error. Comuniquese con administrador</h2>
                <br />
                <h:outputText value="Error Code: #{errorHandler.statusCode}"></h:outputText>
                <br />
                <h:outputText value="Error Desscription: #{errorHandler.message}"></h:outputText>
                <br />
                <h:outputText value="Exception Type: #{errorHandler.exceptionType}"></h:outputText>
                <br />
                <h:outputText value="Exception Calss: #{errorHandler.exception}"></h:outputText>
                <br />
                <h:outputText value="Request URI : #{errorHandler.requestURI}"></h:outputText>
            </ui:define>
        </ui:composition>
        <br/>
        <br/>
        <br/>
        <br/>
    </h:body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      template="/templates/bootstrap.xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <br/>
        <br/>
        <f:loadBundle basename="com.fbaa.jsf.resources.mensajes" var="msg"/>
        <!--        <meta charset="utf-8"/> 
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                
                <h:outputStylesheet name="bootstrap-3.3.4/css/bootstrap.min.css"/>
                <h:outputStylesheet name="bootstrap-3.3.4/css/bootstrap-theme.min.css"/>-->
        <ui:define name="title">
            <h:outputText value="Por favor ingrese sus datos" />
        </ui:define>

    </h:head>
    <h:body>

        <ui:composition template="/templates/commonLayout.xhtml">
            <ui:define name="content">
                <br/>
                <h4>Bienvenidos a la página incial del programa de gestión de voluntariado de la Fundación Banco Arquiciocesano de Alimentos
                </h4>
                <h:form>
                    <h:outputText value="Bienvenido, #{loginBean.usuario}." rendered="#{loginBean.loggedIn}"/>                        
                    <h:commandLink action="#{loginBean.doLogout()}" value="Salir" rendered="#{loginBean.loggedIn}"/>
                </h:form>

                <br/>
                <h:graphicImage library="images" name="BancoFBAA.png" height="10%" width="10%" class="row text-center" />
                <br/>
                <f:view>
                    <br/>
                    <h:form id="ingresar">
                        <h:commandLink action="#{navegacionBean.toLogin()}" value="Ingresar" rendered="#{!loginBean.loggedIn}"/>


                        <br/>
                        <br/>
                    </h:form>
                </f:view> 
            </ui:define>
        </ui:composition>
        <br/>
        <br/>
        <br/>
        <br/>
    </h:body>
</html>

web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      template="/templates/bootstrap.xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>


        <f:loadBundle basename="com.fbaa.jsf.resources.mensajes" var="msg"/>
        <!--        <meta charset="utf-8"/> 
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                
                <h:outputStylesheet name="bootstrap-3.3.4/css/bootstrap.min.css"/>
                <h:outputStylesheet name="bootstrap-3.3.4/css/bootstrap-theme.min.css"/>-->
        <ui:define name="title">
            <h:outputText value="Por favor ingrese sus datos" />
        </ui:define>

    </h:head>
    <h:body>
        
        <ui:composition template="/templates/commonLayout.xhtml">
            <ui:define name="content">
                <h3>Autenticación</h3>
                <f:view>
                    <h:form>
                        <h:messages/>
                        <h:panelGrid columns="1" border="1">
                            <f:facet name="header">
                                <h:outputText value="Por favor ingrese sus datos" />
                            </f:facet>
                            <h:panelGrid columns="3" cellpadding="5" cellspacing="5">
                                Usuario:
                                <h:inputText
                                    value='#{loginBean.usuario}'
                                    id='usernameTextField'
                                    required='true' />
                                <h:message for='usernameTextField' />

                                Contraseña:
                                <h:inputSecret
                                    value='#{loginBean.contrasena}'
                                    id='passwordTextField'
                                    required='true'/>
                                <h:message for='passwordTextField' />

                            </h:panelGrid>

                            <f:facet name="footer">
                                <h:panelGroup style="display:block; text-align:center">
                                    <h:commandButton value='Ingresar' action='#{loginBean.doLogin}' 
                                                     class="btn btn-default btn-primary" />
                                    <!--                                    <h:commandButton value='Ingresar' action='autorizados' 
                                                                                         class="btn btn-default btn-primary" />-->
                                </h:panelGroup>
                            </f:facet>

                        </h:panelGrid>
                    </h:form>
                </f:view> 
            </ui:define>
        </ui:composition>

    </h:body>
</html>